title: "Documenting My CE Journey"
author: "Bismaakram710"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false
#show_frame: "/assets/images/background.svg"
# Menu
navigation:
  # - {file: "archive.html", sidebaricon: home}
  # - {file: "README.md", sidebaricon: address-card}
external:
#  - {title: Mail, icon: envelope, url: "mailto:bismaakram710@gmail.com"}
#  - {title: Github, icon: github, url: "https://github.com/bismaakram710-crypto"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}
comments:
#  disqus_shortname: ""
#  isso_domain: ""
plugins:
 - jekyll-feed
